Add tsfresh 0.18.0
AnacondaRecipes/tsfresh-feedstock pull request #1
Opened 2021-10-06 10:34 UTC by skupr-anaconda

Popularity:  49641 downloads -  tsfresh  0.18.0  Automatic extraction of relevant features from time series
  license: MIT
Release date:  Mar 6, 2021
Bug Tracker: new open issues https://github.com/blue-yonder/tsfresh/issues
Github releases:  https://github.com/blue-yonder/tsfresh/releases
Upstream Changelog: https://github.com/blue-yonder/tsfresh/blob/main/CHANGES.rst
Upstream license file: https://github.com/blue-yonder/tsfresh/blob/v0.18.0/LICENSE.txt
Requirements from conda-forge: https://github.com/conda-forge/tsfresh-feedstock/blob/master/recipe/meta.yaml
Upstream requirements: https://github.com/blue-yonder/tsfresh/blob/v0.18.0/requirements.txt
Upstream setup file: https://github.com/blue-yonder/tsfresh/blob/v0.18.0/setup.py
Upstream setup.cfg: https://github.com/blue-yonder/tsfresh/blob/v0.18.0/setup.cfg

Actions:
1. Add entry_points
2. Update dependencies
3. Disable pip check

Result:
- all-succeeded on concourse

2021-10-06 10:43 UTC, skupr-anaconda commented
We are still waiting when `matrixprofile`'s artifacts will be uploaded on  defaults for`linux-aarch64`, `linux-s390x`, `osx-arm64` https://github.com/AnacondaRecipes/matrixprofile-feedstock/pull/1

2021-10-06 10:50 UTC, katietz requested changes

2021-10-06 10:50 UTC, katietz commented on recipe/meta.yaml
> +    - run_tsfresh = tsfresh.scripts.run_tsfresh:main
We need to add a Jira ticket for osx-arm64 (and linux-aarch64?) and skip those targets (plus a comment)

2021-10-06 11:49 UTC, dbast commented
s390x error: dependency missing `- matrixprofile[version='>=1.1.10,<2.0.0']`

osx-arm64 error: dependency missing `- statsmodels[version='>=0.9.0'] and  - matrixprofile[version='>=1.1.10,<2.0.0']``

linux-aarch64: agent broken... I'll look into that.

2021-10-07 06:08 UTC, katietz approved these changes
Please don't forget to file a Jira ticket for it. So we don't miss it

2021-10-07 06:50 UTC, skupr-anaconda commented
JIRA ticket created: tsfresh 0.18.0 on linux-arm64

2021-10-07 11:30 UTC, skupr-anaconda commented
tsfresh failed on s390x because we can’t build its dependency `stumpy 1.9.2` on this platform, see https://github.com/AnacondaRecipes/stumpy-feedstock/pull/1#issuecomment-935841894

2021-10-07 11:36 UTC, merged